version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Puerto para las conexiones de la aplicación
      - "15672:15672" # Puerto para la interfaz de administración web